var hierarchy =
[
    [ "_BatchNorm1d", null, [
      [ "modules.BatchNorm1d", "classmodules_1_1_batch_norm1d.html", null ]
    ] ],
    [ "_Conv1d", null, [
      [ "modules.Conv1d", "classmodules_1_1_conv1d.html", null ]
    ] ],
    [ "ActivationFunctions", "class_activation_functions.html", null ],
    [ "ASP< channels, attention_channels, input_width, out_width, T >", "class_a_s_p.html", null ],
    [ "ASP< 16, 128, 64, 2, float >", "class_a_s_p.html", null ],
    [ "trainers.BaseTrainer", "classtrainers_1_1_base_trainer.html", null ],
    [ "BasicBlock< kernel, stride, channel_in, channel_out, pad, dilation, input_width, out_width, T >", "class_basic_block.html", null ],
    [ "BasicBlock< 3, 1, 2, 4, 0, 1, 16, 14, float >", "class_basic_block.html", null ],
    [ "BasicBlock< 3, 1, 4, 4, 0, 1, 10, 8, float >", "class_basic_block.html", null ],
    [ "BasicBlock< 3, 1, 4, 4, 0, 1, 12, 10, float >", "class_basic_block.html", null ],
    [ "BasicBlock< 3, 1, 4, 4, 0, 1, 14, 12, float >", "class_basic_block.html", null ],
    [ "BasicBlock< 3, 1, 4, 4, 0, 1, 8, 6, float >", "class_basic_block.html", null ],
    [ "BasicCNNModel", "class_basic_c_n_n_model.html", null ],
    [ "BatchNorm1d< channel, width, T >", "class_batch_norm1d.html", null ],
    [ "BatchNorm1d< 16 *2, 1, float >", "class_batch_norm1d.html", null ],
    [ "BatchNorm1d< channel_out, out_width, float >", "class_batch_norm1d.html", null ],
    [ "BatchNorm1d< channel_out, out_width, T >", "class_batch_norm1d.html", null ],
    [ "saveasfile.BlockSave", "classsaveasfile_1_1_block_save.html", null ],
    [ "Conv1d< kernel, stride, channel_in, channel_out, pad, dilation, input_width, out_width, T >", "class_conv1d.html", null ],
    [ "Conv1d< 1, 1, attention_channels, channels, 0, 1, input_width, input_width, float >", "class_conv1d.html", null ],
    [ "Conv1d< 1, 1, attention_channels, channels, 0, 1, input_width, input_width, T >", "class_conv1d.html", null ],
    [ "Conv1d< 1, 1, channel_in, channel_out, 0, 1, input_width, out_width, float >", "class_conv1d.html", null ],
    [ "Conv1d< 1, 1, channel_in, channel_out, 0, 1, input_width, out_width, T >", "class_conv1d.html", null ],
    [ "Conv1d< 1, 1, channel_in, channel_se, 0, 1, 1, 1, float >", "class_conv1d.html", null ],
    [ "Conv1d< 1, 1, channel_in, channel_se, 0, 1, 1, 1, T >", "class_conv1d.html", null ],
    [ "Conv1d< 1, 1, channel_se, channel_out, 0, 1, 1, 1, float >", "class_conv1d.html", null ],
    [ "Conv1d< 1, 1, channel_se, channel_out, 0, 1, 1, 1, T >", "class_conv1d.html", null ],
    [ "Conv1d< kernel, stride, channel_in, channel_out, input_pad, dilation, input_width, out_width, float >", "class_conv1d.html", null ],
    [ "Conv1d< kernel, stride, channel_in, channel_out, input_pad, dilation, input_width, out_width, T >", "class_conv1d.html", null ],
    [ "Conv1d< kernel, stride, channel_in, channel_out, pad, dilation, input_width, out_width, float >", "class_conv1d.html", null ],
    [ "Dense< input_dim, output_dim, T >", "class_dense.html", null ],
    [ "Dense< 16 *2, 6, float >", "class_dense.html", null ],
    [ "Dense< 24, 6, float >", "class_dense.html", null ],
    [ "ECAPA_TDNN", "class_e_c_a_p_a___t_d_n_n.html", null ],
    [ "Helper", "class_helper.html", null ],
    [ "MatrixFunctions", "class_matrix_functions.html", null ],
    [ "nn.Module", null, [
      [ "modules.AttentiveStatisticsPooling", "classmodules_1_1_attentive_statistics_pooling.html", null ],
      [ "modules.SEBlock", "classmodules_1_1_s_e_block.html", null ],
      [ "modules.SERes2NetBlock", "classmodules_1_1_s_e_res2_net_block.html", null ],
      [ "modules.TDNNBlock", "classmodules_1_1_t_d_n_n_block.html", null ]
    ] ],
    [ "torch.nn.Module", null, [
      [ "BasicModel.BasicModel", "class_basic_model_1_1_basic_model.html", null ],
      [ "modules.Classifier", "classmodules_1_1_classifier.html", null ],
      [ "modules.ECAPA_TDNN", "classmodules_1_1_e_c_a_p_a___t_d_n_n.html", null ],
      [ "modules.Res2NetBlock", "classmodules_1_1_res2_net_block.html", null ]
    ] ],
    [ "Res2NetBlock< kernel, channel_in, channel_out, dilation, input_width, out_width, input_pad, scale, T >", "class_res2_net_block.html", null ],
    [ "Res2NetBlock< kernel, channel_out, channel_out, dilation, input_width, out_width, input_pad, res2net_scale, float >", "class_res2_net_block.html", null ],
    [ "Res2NetBlock< kernel, channel_out, channel_out, dilation, input_width, out_width, input_pad, res2net_scale, T >", "class_res2_net_block.html", null ],
    [ "saveasfile.SaveAsBin", "classsaveasfile_1_1_save_as_bin.html", null ],
    [ "SEBlock< channel_in, channel_se, channel_out, input_width, out_width, T >", "class_s_e_block.html", null ],
    [ "SEBlock< channel_out, channel_se, channel_out, input_width, out_width, float >", "class_s_e_block.html", null ],
    [ "SEBlock< channel_out, channel_se, channel_out, input_width, out_width, T >", "class_s_e_block.html", null ],
    [ "SERes2NetBlock< kernel, channel_in, channel_out, dilation, input_width, out_width, input_pad, res2net_scale, channel_se, T >", "class_s_e_res2_net_block.html", null ],
    [ "SERes2NetBlock< 3, 8, 8, 2, 64, 64, 4, 8, 128, float >", "class_s_e_res2_net_block.html", null ],
    [ "SERes2NetBlock< 3, 8, 8, 3, 64, 64, 6, 8, 128, float >", "class_s_e_res2_net_block.html", null ],
    [ "SERes2NetBlock< 3, 8, 8, 4, 64, 64, 8, 8, 128, float >", "class_s_e_res2_net_block.html", null ],
    [ "TDNNBlock< kernel, stride, channel_in, channel_out, dilation, input_width, out_width, input_pad, T >", "class_t_d_n_n_block.html", null ],
    [ "TDNNBlock< 1, 1, 3 *8, 16, 1, 64, 64, 0, float >", "class_t_d_n_n_block.html", null ],
    [ "TDNNBlock< 1, 1, channel_in, channel_out, 1, input_width, out_width, 0, float >", "class_t_d_n_n_block.html", null ],
    [ "TDNNBlock< 1, 1, channel_in, channel_out, 1, input_width, out_width, 0, T >", "class_t_d_n_n_block.html", null ],
    [ "TDNNBlock< 1, 1, channel_out, channel_out, 1, input_width, out_width, 0, float >", "class_t_d_n_n_block.html", null ],
    [ "TDNNBlock< 1, 1, channel_out, channel_out, 1, input_width, out_width, 0, T >", "class_t_d_n_n_block.html", null ],
    [ "TDNNBlock< 1, 1, channels *3, attention_channels, 1, input_width, input_width, 0, float >", "class_t_d_n_n_block.html", null ],
    [ "TDNNBlock< 1, 1, channels *3, attention_channels, 1, input_width, input_width, 0, T >", "class_t_d_n_n_block.html", null ],
    [ "TDNNBlock< 5, 1, 2, 8, 1, 64, 64, 4, float >", "class_t_d_n_n_block.html", null ],
    [ "TDNNBlock< kernel, 1, channel_in/scale, channel_out/scale, dilation, input_width, out_width, input_pad, float >", "class_t_d_n_n_block.html", null ],
    [ "TDNNBlock< kernel, 1, channel_in/scale, channel_out/scale, dilation, input_width, out_width, input_pad, T >", "class_t_d_n_n_block.html", null ],
    [ "Time", "class_time.html", null ],
    [ "Dataset", null, [
      [ "loaders.RadChar_Dataset", "classloaders_1_1_rad_char___dataset.html", null ]
    ] ]
];